---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/mondash-checkgpg

commands:
  - make publish

environment:
  CGO_ENABLED: 0
  DRAFT: 'false'
  GO111MODULE: on
  MOD_MODE: readonly
